### ISSUE TITLE
suggestion: add ncnn release version

### ISSUE THREAD

**Issue by tpoisonooo** [zeusees/HyperFT#1]
how about adding a prebuilt `libncnn.a` to the project ?

**Comment by panda-lab** [comment]
ok

**Comment by tpoisonooo** [comment]
BTW, hardware platform should be described in the `README.md`,  our test result is 20fps on MI note2 (qcom 821).

An prebuilt apk file could help us to exclude building problem.

**Comment by panda-lab** [comment]
Thank you for your suggestion. This repo use original MTCNN as our detection and tracking model.  We will release modified version mtcnn with faster inference speed. BTW, how about the speed on your device with original face detection MTCNN  model.
