### ISSUE TITLE
项目中人脸跟踪的代码好像还是需要依赖opencv，这个与up主说的不依赖opencv不相符

### ISSUE THREAD

**Issue by qaz734913414** [zeusees/HyperFT#3]

**Comment by panda-lab** [comment]
哪个部分用到了opencv，您发一下，我们看看是否存在问题。

**Comment by qaz734913414** [comment]
CMakeLists.txt中存在opencv sdk的引用
![image](https://user-images.githubusercontent.com/9314219/64680808-13eb5300-d4b1-11e9-9390-3182444900c3.png)
LandmarkTracking.h也存在opencv头文件的引用
![image](https://user-images.githubusercontent.com/9314219/64680913-4b59ff80-d4b1-11e9-941c-8b5c3b8c7153.png)

**Comment by panda-lab** [comment]
尴尬了，这个是可以不用opencv的，暂时先这样，稍后改正。O(∩_∩)O~

**Comment by qaz734913414** [comment]
谢谢分享，期待不依赖opencv的版本
